version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "PLACEHOLDER_TASK_DEF_ARN"
        LoadBalancerInfo:
          ContainerName: ecs-url-shortener-container
          ContainerPort: 8000
        PlatformVersion: LATEST