name: Deploy to ECS

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Image tag (leave empty for latest)'
        required: false
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-2
      ECS_TASK_FAMILY: ecs-url-shortener-task
      CODEDEPLOY_APP: url-shortener-codedeploy-app
      CODEDEPLOY_GROUP: url-shortener-dg
      S3_BUCKET: url-shortener-848153448908-codedeploy-revisions

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      